export const products = [
  {
    name: "Brinjal",
    price: "Rs 60",
    image: "assets/images/products-imgs/potato.jpg",
    tag: "Popular",
  },
  {
    name: "Tomato",
    price: "Rs 799",
    image: "assets/images/products-imgs/cap.jpg",
    discount: "10% OFF",
  },
  {
    name: "Carrot",
    price: "Rs 80",
    image: "assets/images/products-imgs/potato.jpg",
  },
  {
    name: "Capsicum",
    price: "Rs 100",
    image: "assets/images/products-imgs/tometo.jpg",
    tag: "New",
  },
  {
    name: "Potato",
    price: "Rs 50",
    image: "assets/images/products-imgs/tometo.jpg",
  },
  {
    name: "Onion",
    price: "Rs 40",
    image: "assets/images/products-imgs/potato.jpg",
    discount: "5% OFF",
  },
  {
    name: "Cucumber",
    price: "Rs 70",
    image: "assets/images/products-imgs/tometo.jpg",
  },
  {
    name: "Beetroot",
    price: "Rs 90",
    image: "assets/images/products-imgs/cap.jpg",
    tag: "Organic",
  },
];

export const productsList = [
  {
    id: 1,
    name: "Organic Tomatoes",
    description:
      "Fresh organic tomatoes grown locally with no pesticides. Perfect for salads and cooking.",
    image: "https://images.unsplash.com/photo-1592841200221-a6895c5a0d4a",
    category_id: 1,
    category: { name: "Vegetables" },
    price: 120,
    originalPrice: 150,
    discount: 20,
    rating: 4.5,
    reviews: 24,
    stock: 15,
  },
  {
    id: 2,
    name: "Premium Basmati Rice",
    description:
      "Aromatic long grain basmati rice imported directly from India. 5kg pack.",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
    category_id: 2,
    category: { name: "Grains" },
    price: 450,
    originalPrice: 500,
    discount: 10,
    rating: 4.2,
    reviews: 18,
    stock: 8,
  },
  {
    id: 3,
    name: "Basmati Rice",
    description:
      "Aromatic long grain basmati rice imported directly from India. 5kg pack.",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
    category_id: 2,
    category: { name: "Grains" },
    price: 40,
    originalPrice: 100,
    discount: 10,
    rating: 4.2,
    reviews: 18,
    stock: 8,
  },
  {
    id: 4,
    name: "Rice",
    description:
      "Aromatic long grain basmati rice imported directly from India. 5kg pack.",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
    category_id: 2,
    category: { name: "Grains" },
    price: 50,
    originalPrice: 100,
    discount: 10,
    rating: 4.2,
    reviews: 18,
    stock: 8,
  },
  {
    id: 5,
    name: "Rice",
    description:
      "Aromatic long grain basmati rice imported directly from India. 5kg pack.",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
    category_id: 2,
    category: { name: "Grains" },
    price: 50,
    originalPrice: 90,
    discount: 10,
    rating: 4.2,
    reviews: 18,
    stock: 8,
  },
];
