// /data/blogPosts.js

export const blogPosts = [
    {
      id: 1,
      title: "Why React is Still Dominating Frontend Development in 2025",
      excerpt: "React continues to be the go-to choice for building modern web applications...",
      content: {
        introduction: "React has evolved significantly since its initial release...",
        features: [
          "Server Components for improved performance",
          "Enhanced Suspense for better loading states",
          "Improved compiler optimizations",
        ],
        conclusion: "The future of React looks brighter than ever...",
      },
      image: "https://source.unsplash.com/random/1200x800?reactjs,development",
      date: "April 8, 2025",
      author: "Sarah Johnson",
      readTime: "6 min",
      tags: ["React", "Frontend", "JavaScript"],
    },
    {
        id: 2,
        title: "Why React is Still Dominating Frontend Development in 2025",
        excerpt: "React continues to be the go-to choice for building modern web applications...",
        content: {
          introduction: "React has evolved significantly since its initial release...",
          features: [
            "Server Components for improved performance",
            "Enhanced Suspense for better loading states",
            "Improved compiler optimizations",
          ],
          conclusion: "The future of React looks brighter than ever...",
        },
        image: "https://source.unsplash.com/random/1200x800?reactjs,development",
        date: "April 8, 2025",
        author: "Sarah Johnson",
        readTime: "6 min",
        tags: ["React", "Frontend", "JavaScript"],
      },
      {
        id: 3,
        title: "Why React is Still Dominating Frontend Development in 2025",
        excerpt: "React continues to be the go-to choice for building modern web applications...",
        content: {
          introduction: "React has evolved significantly since its initial release...",
          features: [
            "Server Components for improved performance",
            "Enhanced Suspense for better loading states",
            "Improved compiler optimizations",
          ],
          conclusion: "The future of React looks brighter than ever...",
        },
        image: "https://source.unsplash.com/random/1200x800?reactjs,development",
        date: "April 8, 2025",
        author: "Sarah Johnson",
        readTime: "6 min",
        tags: ["React", "Frontend", "JavaScript"],
      },
      {
        id: 4,
        title: "Why React is Still Dominating Frontend Development in 2025",
        excerpt: "React continues to be the go-to choice for building modern web applications...",
        content: {
          introduction: "React has evolved significantly since its initial release...",
          features: [
            "Server Components for improved performance",
            "Enhanced Suspense for better loading states",
            "Improved compiler optimizations",
          ],
          conclusion: "The future of React looks brighter than ever...",
        },
        image: "https://source.unsplash.com/random/1200x800?reactjs,development",
        date: "April 8, 2025",
        author: "Sarah Johnson",
        readTime: "6 min",
        tags: ["React", "Frontend", "JavaScript"],
      },
      {
          id: 5,
          title: "Why React is Still Dominating Frontend Development in 2025",
          excerpt: "React continues to be the go-to choice for building modern web applications...",
          content: {
            introduction: "React has evolved significantly since its initial release...",
            features: [
              "Server Components for improved performance",
              "Enhanced Suspense for better loading states",
              "Improved compiler optimizations",
            ],
            conclusion: "The future of React looks brighter than ever...",
          },
          image: "https://source.unsplash.com/random/1200x800?reactjs,development",
          date: "April 8, 2025",
          author: "Sarah Johnson",
          readTime: "6 min",
          tags: ["React", "Frontend", "JavaScript"],
        },
        {
          id: 6,
          title: "Why React is Still Dominating Frontend Development in 2025",
          excerpt: "React continues to be the go-to choice for building modern web applications...",
          content: {
            introduction: "React has evolved significantly since its initial release...",
            features: [
              "Server Components for improved performance",
              "Enhanced Suspense for better loading states",
              "Improved compiler optimizations",
            ],
            conclusion: "The future of React looks brighter than ever...",
          },
          image: "https://source.unsplash.com/random/1200x800?reactjs,development",
          date: "April 8, 2025",
          author: "Sarah Johnson",
          readTime: "6 min",
          tags: ["React", "Frontend", "JavaScript"],
        },
        {
            id: 7,
            title: "Why React is Still Dominating Frontend Development in 2025",
            excerpt: "React continues to be the go-to choice for building modern web applications...",
            content: {
              introduction: "React has evolved significantly since its initial release...",
              features: [
                "Server Components for improved performance",
                "Enhanced Suspense for better loading states",
                "Improved compiler optimizations",
              ],
              conclusion: "The future of React looks brighter than ever...",
            },
            image: "https://source.unsplash.com/random/1200x800?reactjs,development",
            date: "April 8, 2025",
            author: "Sarah Johnson",
            readTime: "6 min",
            tags: ["React", "Frontend", "JavaScript"],
          },
          {
              id: 8,
              title: "Why React is Still Dominating Frontend Development in 2025",
              excerpt: "React continues to be the go-to choice for building modern web applications...",
              content: {
                introduction: "React has evolved significantly since its initial release...",
                features: [
                  "Server Components for improved performance",
                  "Enhanced Suspense for better loading states",
                  "Improved compiler optimizations",
                ],
                conclusion: "The future of React looks brighter than ever...",
              },
              image: "https://source.unsplash.com/random/1200x800?reactjs,development",
              date: "April 8, 2025",
              author: "Sarah Johnson",
              readTime: "6 min",
              tags: ["React", "Frontend", "JavaScript"],
            },
            {
              id: 9,
              title: "Why React is Still Dominating Frontend Development in 2025",
              excerpt: "React continues to be the go-to choice for building modern web applications...",
              content: {
                introduction: "React has evolved significantly since its initial release...",
                features: [
                  "Server Components for improved performance",
                  "Enhanced Suspense for better loading states",
                  "Improved compiler optimizations",
                ],
                conclusion: "The future of React looks brighter than ever...",
              },
              image: "https://source.unsplash.com/random/1200x800?reactjs,development",
              date: "April 8, 2025",
              author: "Sarah Johnson",
              readTime: "6 min",
              tags: ["React", "Frontend", "JavaScript"],
            },
            {
              id: 10,
              title: "Why React is Still Dominating Frontend Development in 2025",
              excerpt: "React continues to be the go-to choice for building modern web applications...",
              content: {
                introduction: "React has evolved significantly since its initial release...",
                features: [
                  "Server Components for improved performance",
                  "Enhanced Suspense for better loading states",
                  "Improved compiler optimizations",
                ],
                conclusion: "The future of React looks brighter than ever...",
              },
              image: "https://source.unsplash.com/random/1200x800?reactjs,development",
              date: "April 8, 2025",
              author: "Sarah Johnson",
              readTime: "6 min",
              tags: ["React", "Frontend", "JavaScript"],
            },
            {
                id: 11,
                title: "Why React is Still Dominating Frontend Development in 2025",
                excerpt: "React continues to be the go-to choice for building modern web applications...",
                content: {
                  introduction: "React has evolved significantly since its initial release...",
                  features: [
                    "Server Components for improved performance",
                    "Enhanced Suspense for better loading states",
                    "Improved compiler optimizations",
                  ],
                  conclusion: "The future of React looks brighter than ever...",
                },
                image: "https://source.unsplash.com/random/1200x800?reactjs,development",
                date: "April 8, 2025",
                author: "Sarah Johnson",
                readTime: "6 min",
                tags: ["React", "Frontend", "JavaScript"],
              },
              {
                id: 12,
                title: "Why React is Still Dominating Frontend Development in 2025",
                excerpt: "React continues to be the go-to choice for building modern web applications...",
                content: {
                  introduction: "React has evolved significantly since its initial release...",
                  features: [
                    "Server Components for improved performance",
                    "Enhanced Suspense for better loading states",
                    "Improved compiler optimizations",
                  ],
                  conclusion: "The future of React looks brighter than ever...",
                },
                image: "https://source.unsplash.com/random/1200x800?reactjs,development",
                date: "April 8, 2025",
                author: "Sarah Johnson",
                readTime: "6 min",
                tags: ["React", "Frontend", "JavaScript"],
              }
  ];
  